**Michelle Sophia A. Abamonga**\
2 -ECEB\
PA 2 - NUMERICAL PYTHON (NUMPY)

## A. NORMALIZATION PROBLEM
In this problem, create a random 5 x 5 ndarray and store it to variable X. Normalize X. Save your normalized
ndarray as X_normalized.npy

#### 1. Import the NumPy library in Python
Assign numpy the alias **np** for easier reference.

In [4]:
import numpy as np

#### 2. Create a randomized 5x5 ndarray and store it in variable X

In this particular syntax the function **np.random.rand()** generates an array of random floating-point numbers between 0 and 1, based on the dimensions specified by the user (5 row and 5 columns). 

On the other hand, to generate random integers, the function **np.random.randint()** should be used.

In [6]:
X = np.random.rand(5, 5)

X

array([[0.30042608, 0.46480332, 0.045934  , 0.93659386, 0.06171676],
       [0.04637648, 0.51313869, 0.84898423, 0.48414989, 0.69887532],
       [0.98313454, 0.41401875, 0.33570859, 0.85389833, 0.42972917],
       [0.48671498, 0.00146986, 0.73953109, 0.0972859 , 0.52859453],
       [0.34320433, 0.85433735, 0.92599281, 0.19761735, 0.96187277]])

#### 3. Calculate the mean

In this syntax, the **np.mean()** function calculates the mean (average) of the array X. It is a built-in function provided by NumPy.

In [8]:
mean = np.mean(X)

mean

0.5021643601833532

#### 4. Calculate the standard deviation of X

In this syntax, the **np.std()** function calculates the standard deviation of the array X. It is also a built-in function provided by NumPy.

In [10]:
std = np.std(X)

std

0.3162790177002085

#### 5. Normalize X using the formula: Z = (X - mean) / std

With the formula to normalize the array: **Z = (X - mean) / std**, the function **X_normalized** is defined. The given formula is particularly used for Z-score normalization, also known as standardization. This is a method of scaling data so that it has a mean of 0 and a standard deviation of 1. 

In [12]:
X_normalized = (X - mean) / std

X_normalized

array([[-0.63784909, -0.11812684, -1.44249329,  1.37356409, -1.39259189],
       [-1.44109428,  0.03469827,  1.09656302, -0.05695752,  0.62195388],
       [ 1.5207148 , -0.27869571, -0.52629406,  1.11210024, -0.22902308],
       [-0.04884731, -1.58307847,  0.75049788, -1.28013064,  0.083566  ],
       [-0.50259429,  1.1134883 ,  1.34004604, -0.96290613,  1.45349008]])

#### 6. Save the normalized ndarray as X_normalized.npy
The np.save() function saves the normalized ndarray to a specified file location, which is automatically generated when the code is executed. The syntax follows the format np.save('filename', array).

In [14]:
np.save("X_normalized.npy", X_normalized)

## B. DIVISIBLE BY 3 PROBLEM
In this problem, create a 10 x 10 ndarray which are the squares of the first 100 positive integers. From this ndarray, determine all the elements that are divisible by 3. Save the result as div_by_3.np.yy

#### 1. Import the NumPy library in Python
Assign numpy the alias **np** for easier reference.

In [16]:
import numpy as np

#### 2. Create array of integers from 1 to 100, squaring each integer
In this syntax, the function **np.arange(1, 101)** generates a NumPy array of integers from 1 to 100 (101 is excluded). The exponentiation operator **2 then squares each element in the array, raising every number from 1 to 100 to the power of 2.

**np.arange()** is typically used with the syntax np.arange(start, stop, step), where start is the first number in the range, stop is the end number (exclusive), and step defines the interval between values

In [17]:
A = np.arange(1, 101)**2

A

array([    1,     4,     9,    16,    25,    36,    49,    64,    81,
         100,   121,   144,   169,   196,   225,   256,   289,   324,
         361,   400,   441,   484,   529,   576,   625,   676,   729,
         784,   841,   900,   961,  1024,  1089,  1156,  1225,  1296,
        1369,  1444,  1521,  1600,  1681,  1764,  1849,  1936,  2025,
        2116,  2209,  2304,  2401,  2500,  2601,  2704,  2809,  2916,
        3025,  3136,  3249,  3364,  3481,  3600,  3721,  3844,  3969,
        4096,  4225,  4356,  4489,  4624,  4761,  4900,  5041,  5184,
        5329,  5476,  5625,  5776,  5929,  6084,  6241,  6400,  6561,
        6724,  6889,  7056,  7225,  7396,  7569,  7744,  7921,  8100,
        8281,  8464,  8649,  8836,  9025,  9216,  9409,  9604,  9801,
       10000])

#### 3. Reshape array into 10x10 ndarray 
A one-dimensional array can be reshaped into a custom set of dimensions. In this syntax, Array A is reshaped into a 10x10 ndarray using the **.reshape()** function, with 10 rows and 10 columns, while retaining the same set of elements.

In [18]:
A = A.reshape(10, 10)

A

array([[    1,     4,     9,    16,    25,    36,    49,    64,    81,
          100],
       [  121,   144,   169,   196,   225,   256,   289,   324,   361,
          400],
       [  441,   484,   529,   576,   625,   676,   729,   784,   841,
          900],
       [  961,  1024,  1089,  1156,  1225,  1296,  1369,  1444,  1521,
         1600],
       [ 1681,  1764,  1849,  1936,  2025,  2116,  2209,  2304,  2401,
         2500],
       [ 2601,  2704,  2809,  2916,  3025,  3136,  3249,  3364,  3481,
         3600],
       [ 3721,  3844,  3969,  4096,  4225,  4356,  4489,  4624,  4761,
         4900],
       [ 5041,  5184,  5329,  5476,  5625,  5776,  5929,  6084,  6241,
         6400],
       [ 6561,  6724,  6889,  7056,  7225,  7396,  7569,  7744,  7921,
         8100],
       [ 8281,  8464,  8649,  8836,  9025,  9216,  9409,  9604,  9801,
        10000]])

#### 4. Determine the elements divisible by 3

**A % 3 == 0** checks each element in array A to see if it is divisible by 3. The modulo operator (%) returns the remainder when each element is divided by 3.
Meanwhile, **A[A % 3 == 0]** a boolean indexing, filters the array A and returns only the elements where the condition A % 3 == 0 is True. Essentially, it creates a new array that contains only the elements from A that are divisible by 3

These are then defined in the function name **div_by_3**.

In [19]:
div_by_3 = A[A % 3 == 0]

div_by_3

array([   9,   36,   81,  144,  225,  324,  441,  576,  729,  900, 1089,
       1296, 1521, 1764, 2025, 2304, 2601, 2916, 3249, 3600, 3969, 4356,
       4761, 5184, 5625, 6084, 6561, 7056, 7569, 8100, 8649, 9216, 9801])

#### 5. Save the result in another file
The np.save() function saves the normalized ndarray to a specified file location, automatically generated when the code is executed. The syntax follows the format np.save('filename', array).

In [20]:
np.save('div_by_3.npy', div_by_3)