**Michelle Sophia A. Abamonga**\
2 -ECEB\
PA 2 - NUMERICAL PYTHON (NUMPY)

## NORMALIZATION PROBLEM
In this problem, create a random 5 x 5 ndarray and store it to variable X. Normalize X. Save your normalized
ndarray as X_normalized.npy

In [8]:
import numpy as np

In [44]:
#Create a randomized 5x5 ndarray and store it in variable X
X = np.random.rand(5, 5)

X

array([[0.26256697, 0.09802344, 0.33544294, 0.58002692, 0.41463787],
       [0.78449554, 0.74121957, 0.27853559, 0.8312426 , 0.19848271],
       [0.74820316, 0.05998456, 0.7437726 , 0.6306434 , 0.31057244],
       [0.99652952, 0.48539258, 0.72587531, 0.57141517, 0.83280102],
       [0.93472515, 0.14293943, 0.82180642, 0.90296696, 0.07540151]])

In [50]:
#Calculate the mean
mean = np.mean(X)

mean

0.540308135324447

In [52]:
#Calculate the standard deviation of X
std = np.std(X)

std

0.2933152188247287

In [54]:
#Normalize X using the formula: Z = (X - mean) / std
X_normalized = (X - mean) / std

X_normalized

array([[-0.94690335, -1.50788184, -0.69844721,  0.13541332, -0.42844783],
       [ 0.83250848,  0.68496763, -0.8924615 ,  0.9918833 , -1.1653859 ],
       [ 0.70877682, -1.63756787,  0.6936717 ,  0.30798014, -0.78323824],
       [ 1.55539624, -0.18722368,  0.63265442,  0.10605325,  0.99719642],
       [ 1.34468651, -1.35474971,  0.95971249,  1.23641325, -1.58500684]])

In [57]:
#Save the normalized ndarray as X_normalized.npy
np.save("X_normalized.npy", X_normalized)

## DIVISIBLE BY 3 PROBLEM
In this problem, create a 10 x 10 ndarray which are the squares of the first 100 positive integers. From this ndarray, determine all the elements that are divisible by 3. Save the result as div_by_3.np.yy

In [76]:
import numpy as np

In [78]:
#Create array of integers from 1 to 100, squaring each integer
A = np.arange(1, 101)**2

A

array([    1,     4,     9,    16,    25,    36,    49,    64,    81,
         100,   121,   144,   169,   196,   225,   256,   289,   324,
         361,   400,   441,   484,   529,   576,   625,   676,   729,
         784,   841,   900,   961,  1024,  1089,  1156,  1225,  1296,
        1369,  1444,  1521,  1600,  1681,  1764,  1849,  1936,  2025,
        2116,  2209,  2304,  2401,  2500,  2601,  2704,  2809,  2916,
        3025,  3136,  3249,  3364,  3481,  3600,  3721,  3844,  3969,
        4096,  4225,  4356,  4489,  4624,  4761,  4900,  5041,  5184,
        5329,  5476,  5625,  5776,  5929,  6084,  6241,  6400,  6561,
        6724,  6889,  7056,  7225,  7396,  7569,  7744,  7921,  8100,
        8281,  8464,  8649,  8836,  9025,  9216,  9409,  9604,  9801,
       10000])

In [80]:
#Reshape array into 10x10 ndarray 
A = A.reshape(10, 10)

A

array([[    1,     4,     9,    16,    25,    36,    49,    64,    81,
          100],
       [  121,   144,   169,   196,   225,   256,   289,   324,   361,
          400],
       [  441,   484,   529,   576,   625,   676,   729,   784,   841,
          900],
       [  961,  1024,  1089,  1156,  1225,  1296,  1369,  1444,  1521,
         1600],
       [ 1681,  1764,  1849,  1936,  2025,  2116,  2209,  2304,  2401,
         2500],
       [ 2601,  2704,  2809,  2916,  3025,  3136,  3249,  3364,  3481,
         3600],
       [ 3721,  3844,  3969,  4096,  4225,  4356,  4489,  4624,  4761,
         4900],
       [ 5041,  5184,  5329,  5476,  5625,  5776,  5929,  6084,  6241,
         6400],
       [ 6561,  6724,  6889,  7056,  7225,  7396,  7569,  7744,  7921,
         8100],
       [ 8281,  8464,  8649,  8836,  9025,  9216,  9409,  9604,  9801,
        10000]])

In [68]:
#Determine the elements divisible by 3
div_by_3 = A[A % 3 == 0]

div_by_3

array([   9,   36,   81,  144,  225,  324,  441,  576,  729,  900, 1089,
       1296, 1521, 1764, 2025, 2304, 2601, 2916, 3249, 3600, 3969, 4356,
       4761, 5184, 5625, 6084, 6561, 7056, 7569, 8100, 8649, 9216, 9801])

In [70]:
#Save the result
np.save('div_by_3.npy', div_by_3)